// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Noisy;
RWTexture2D<float4> History;
RWTexture2D<float4> Denoised;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Denoised[id.xy] = lerp(Noisy[id.xy], History[id.xy], 0.9);
}




